services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "8801:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - network

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres8888
    ports:
      - "8802:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - network
    restart: always
  
  minio:
    image: quay.io/minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio8888
    command: server /data --address :8007 --console-address :8006
    ports:
      - "8803:8007"
      - "8804:8006"
    volumes:
      - minio-data:/data
    networks:
      - network
    restart: always

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "8805:6333"
    volumes:
      - qdrant-data:/qdrant/storage
    networks:
      - network
    restart: always

  neo4j:
    image: neo4j
    container_name: neo4j
    environment:
      - NEO4J_AUTH=neo4j/neo4j8888
    ports:
      - "8806:7474"   # Neo4j browser
      - "8807:7687"   # Bolt protocol
    volumes:
      - neo4j-data:/data
    networks:
      - network
    restart: always

  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: clickhouse
    environment:
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: admin8888
    ports:
      - "8808:9000"   # Native client port
      - "8809:8123"   # HTTP interface (optional)
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    networks:
      - network
    restart: always

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "8810:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - network
    restart: always

volumes:
  mongodb-data:
  postgres-data: 
  minio-data:
  qdrant-data:
  neo4j-data:
  clickhouse-data:
  redis-data:

networks:
  network:

